cml-pr

diff --git a/.github/workflows/cml.yaml b/.github/workflows/cml.yaml
--- a/.github/workflows/cml.yaml
+++ b/.github/workflows/cml.yaml
@@ -9,8 +9,6 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - uses: iterative/setup-cml@v1
-
       - uses: iterative/setup-dvc@v1
 
       - uses: actions/setup-python@v2
@@ -24,6 +22,8 @@ jobs:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         run: |
+          npm install -g git://github.com/iterative/cml.git#cml-pr --save 
+
           git fetch --prune --unshallow
           
           pip install -r requirements.txt
@@ -37,14 +37,13 @@ jobs:
           echo 'DVC push cache'
           dvc push --run-cache -v
 
-          echo 'CML Report' > report.md
+          cml-pr --new-pr 'dvc.lock' '.gitignore' './**/*.json'
 
-          echo 'Use DVC metrics diff to compare metrics to master'
-          (dvc metrics diff -v --show-md master >> report.md ) || echo 'Failed diff'
-          
-          echo 'Add figure to report'
-          (dvc plots diff -v --target loss.csv --show-vega master > vega.json && \
-          vl2png vega.json -s 1.3 | cml-publish --md >> report.md) || echo 'Failed plots diff'
+          echo 'CML Report' > report.md
+          ((dvc metrics diff -v --show-md master) || echo 'Failed diff') >> report.md
+
+          ((dvc plots diff -v --target loss.csv --show-vega master > vega.json && \
+          vl2png vega.json -s 1.3 | cml-publish --md) || echo 'Failed plots diff') >> report.md
 
           echo 'Send report'
           cml-send-comment report.md 
